// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import playwright from 'eslint-plugin-playwright';

export default tseslint.config(
  // ── Global ignores ────────────────────────────────────────────────
  {
    ignores: [
      // Dependencies
      'node_modules/',
      // Hybrid Architecture runtime output (artifacts/ is the canonical dir)
      'artifacts/',
      'test-results/',
      'playwright-report/',
      'blob-report/',
      'reports/',
      // Auth session state
      '.auth/',
      // MCP build outputs
      'tools/mcp/dist/',
      // Compiled env loader (generated by mcp:build, not source of truth)
      'src/utils/*.js',
      'src/utils/*.d.ts',
      // Synced file-content-core copy inside MCP server (single source of truth is src/)
      'tools/mcp/src/utils/file-content-core.ts',
      // Playwright config copies under config/
      'config/playwright/',
    ],
  },

  // ── Base: ESLint + TypeScript recommended ─────────────────────────
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ── TypeScript file overrides ─────────────────────────────────────
  {
    files: ['**/*.ts'],
    rules: {
      // Relax rules yang terlalu strict untuk test code
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
    },
  },

  // ── Playwright test files (Hybrid Architecture: tests/ workspace) ──
  {
    files: ['tests/**/*.spec.ts', 'examples/**/*.spec.ts'],
    ...playwright.configs['flat/recommended'],
    rules: {
      ...playwright.configs['flat/recommended'].rules,
      // expect().toBeTruthy() pattern yang kita pakai di smoke test
      'playwright/no-conditional-in-test': 'warn',
      // Disable expect-expect warning since page objects contain assertions
      'playwright/expect-expect': 'off',
    },
  },

  // ── Standalone Node scripts (.mjs / .cjs) — Node env, not browser ─
  {
    files: [
      'tools/scripts/**/*.mjs',
      'tools/scripts/**/*.cjs',
      'scripts/**/*.mjs',
      'scripts/**/*.cjs',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        URL: 'readonly',
      },
    },
    rules: {
      'no-undef': 'off', // Node globals registered above; TypeScript handles imports
    },
  },
);
