/// <reference types="node" />
/**
 * wizard-auth-template — Generate src/support/auth.setup.ts untuk custom project
 *
 * Template auth setup generic tanpa dependency ke POM atau ERPKU-specific code.
 * Menggunakan selector HTML umum yang bekerja di mayoritas aplikasi web.
 *
 * @module scripts/wizard-auth-template
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

export interface AuthRole {
  /** Nama role, lowercase-hyphen. Misal: 'admin', 'super-admin', 'user' */
  name: string;
  /** Path file auth state yang akan disimpan. Misal: '.auth/admin.json' */
  authFile: string;
}

export interface AuthTemplateOptions {
  roles: AuthRole[];
  /** Path URL halaman login. Misal: '/login' */
  loginUrl: string;
  /** Path URL setelah login berhasil. Misal: '/dashboard' */
  successUrlPath: string;
}

/**
 * Generate isi file auth.setup.ts generik untuk satu atau banyak role.
 * Setiap role menggunakan env var tersendiri: {ROLE}_EMAIL, {ROLE}_PASSWORD.
 * Role tunggal (default/user) fallback ke TEST_USER_EMAIL / TEST_USER_PASSWORD.
 */
export function generateAuthSetupContent(opts: AuthTemplateOptions): string {
  const { roles, loginUrl, successUrlPath } = opts;

  const roleBlocks = roles
    .map((role) => {
      const envPrefix =
        role.name === 'default' || role.name === 'user'
          ? 'TEST_USER'
          : role.name.toUpperCase().replace(/-/g, '_');

      return `
setup('authenticate:${role.name}', async ({ page }) => {
  const authFile = '${role.authFile}';

  // Cek session masih valid
  if (fs.existsSync(authFile)) {
    try {
      await page.goto(process.env.BASE_URL! + '${successUrlPath}');
      if (!page.url().includes('${loginUrl}')) {
        console.log('✔ [Auth] Session ${role.name} masih valid, skip login.');
        await page.context().storageState({ path: authFile });
        return;
      }
    } catch {
      console.log('⚠ [Auth] Gagal cek session ${role.name}, login ulang...');
    }
  }

  // Login
  await page.goto(process.env.BASE_URL! + '${loginUrl}');

  // Isi form — wizard menggunakan selector umum
  // Jika selector tidak cocok, minta Hermes: "Tolong perbaiki auth.setup.ts"
  await page.fill(
    'input[type="email"], input[name="email"], input[name="username"], input[id*="email"], input[id*="user"]',
    process.env.${envPrefix}_EMAIL ?? process.env.TEST_USER_EMAIL ?? '',
  );
  await page.fill(
    'input[type="password"], input[name="password"], input[id*="pass"]',
    process.env.${envPrefix}_PASSWORD ?? process.env.TEST_USER_PASSWORD ?? '',
  );
  await page.click(
    'button[type="submit"], input[type="submit"], button:has-text("Login"), button:has-text("Masuk"), button:has-text("Sign in"), button:has-text("Log in")',
  );

  await page.waitForURL('**${successUrlPath}**', { timeout: 20_000 });
  await page.context().storageState({ path: authFile });
  console.log('✔ [Auth] Session ${role.name} tersimpan di', authFile);
});`;
    })
    .join('\n');

  return `import { test as setup } from '@playwright/test';
import * as fs from 'fs';

/**
 * Auth Setup — generated by setup:wizard
 *
 * File ini di-generate otomatis. Aman untuk diedit manual.
 * Jika selector form login tidak cocok, minta bantuan Hermes:
 *   "Tolong perbaiki src/support/auth.setup.ts untuk login page di {BASE_URL}${loginUrl}"
 *
 * Jalankan manual: npx playwright test src/support/auth.setup.ts --project=setup
 */
${roleBlocks}
`;
}

/**
 * Tulis file auth.setup.ts ke disk, buat direktori jika belum ada.
 * Jika file sudah ada, backup ke `<outPath>.bak` sekali sebelum overwrite.
 */
export function writeAuthSetup(opts: AuthTemplateOptions, outPath: string): void {
  const dir = path.dirname(outPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  if (fs.existsSync(outPath)) {
    const bak = outPath + '.bak';
    try {
      fs.copyFileSync(outPath, bak);
    } catch {
      // non-fatal — still write new content
    }
  }
  fs.writeFileSync(outPath, generateAuthSetupContent(opts), 'utf-8');
}
